configuration:
  - Debug
  - Release

image: Visual Studio 2017

environment:
  RunCodeAnalysis: true
  TreatWarningsAsErrors: true

branches:
  only:
    - master
    - develop

skip_tags: true

notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true

cache:
  - packages -> **\packages.config

install:
  - nuget restore

build:
  parallel: true

after_build:
  - nuget pack src\RestartManager.PowerShell\RestartManager.nuspec -OutputDirectory bin\%configuration% -Version %GitBuildVersionSimple% -Symbols -NoPackageAnalysis -Properties "Configuration=%configuration%;CommitId=%APPVEYOR_REPO_COMMIT%"

test:
  assemblies:
    only:
      - test\**\bin\$(configuration)\*.test.dll

artifacts:
  - path: bin\$(configuration)\*.nupkg
  - path: src\RestartManager.PowerShell\bin\$(configuration)
    name: RestartManager
    type: zip

nuget:
  project_feed: true

deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/heaths
    api_key:
      secure: FD8o+SxdA+nxTC1GRb5381yjQXgRS+B/8dtxyaWllpg=
    artifact: /.*\.symbols\.nupkg/
    on:
      configuration: Release